checks:
    python:
        code_rating: true
        duplicate_code: true
build:
    environment:
        python: 3.6.3
    nodes:
        analysis:
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - py-scrutinizer-run
                    -
                        command: pylint-run
                        use_website_config: true
        coverage:
            tests:
                override:
                    - command: python manage.py test
                    coverage:
                        file: .coverage
                        config_file: .coveragerc
                        format: python-cc
filter:
    excluded_paths:
        - '*/test/*'
        - '*/migrations/*'
    dependency_paths:
        - 'lib/*'
